import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import { geist, inter, jetbrains } from "./Fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` h-full antialiased ${geist.variable} ${jetbrains.variable} ${inter.variable}`}
    >
      <body className="min-h-full flex flex-col bg-neutral text-neutral-100">

        <div className="fixed inset-0 overflow-hidden pointer-events-none -z-10">
          <div className="glow-sphere animate-blob-1 absolute top-1/4 right-0 w-[500px] h-[500px] bg-primary rounded-full"></div>

          <div className="glow-sphere animate-blob-2 absolute bottom-0 left-1/6 w-[400px] h-[400px] bg-tertiary rounded-full"></div>
        </div>
        <Navbar />
        <section className="min-h-[calc(100vh-170px)]">
          {children}
        </section>
        <Footer />
      </body>
    </html>
  );
}
